# Examples Lecture 1b
# Curve fitting 1 and interpolation


## Vandermonde
### Example 17.1 Python book   

In [15]:
import numpy as np

# Given data points
x = np.array([300, 400, 500])
y = np.array([0.616, 0.525, 0.457])

# Construct Vandermonde matrix for a quadratic polynomial (degree 2)
V = np.vander(x, 3)

# Solve for polynomial coefficients
coeffs = np.linalg.solve(V, y)

print("Polynomial coefficients (a, b, c) for ax^2 + bx + c:")
print(coeffs)

Polynomial coefficients (a, b, c) for ax^2 + bx + c:
[ 1.150e-06 -1.715e-03  1.027e+00]


In [16]:
# print the vandermonde matrix
print("\nVandermonde matrix:")
print(V)


Vandermonde matrix:
[[ 90000    300      1]
 [160000    400      1]
 [250000    500      1]]


In [17]:
# Evaluate the polynomial at a new point, e.g., x = 350
x_new = 350
y_new = np.polyval(coeffs[::-1], x_new)
print(f"Estimated value at x = {x_new}: {y_new}")

Estimated value at x = 350: 125806.89975114993


In [18]:
# results above seems wrong. Calculate the polynomial coefficients directly
coeffs_direct = np.polyfit(x, y, 2)
print("Polynomial coefficients (a, b, c) for ax^2 + bx + c (direct calculation):")
print(coeffs_direct)

Polynomial coefficients (a, b, c) for ax^2 + bx + c (direct calculation):
[ 1.150e-06 -1.715e-03  1.027e+00]


In [19]:
a = coeffs_direct[0]
b = coeffs_direct[1]
c = coeffs_direct[2]
a*x_new**2 + b*x_new + c

np.float64(0.567625)

In [20]:
# use polyval to evaluate the polynomial at the new point
y_new_direct = np.polyval(coeffs_direct[::1], x_new)
print(f"Estimated value at x = {x_new} (direct calculation): {y_new_direct}")


Estimated value at x = 350 (direct calculation): 0.5676249999999999


### Newton difference interpolation

In [21]:
import numpy as np

def Newtint(x,y,xx):
    """
    Newtint: Newton interpolating polynomial
    Uses an (n-1)th-order Newton interpolating polynomial
    based on n data pairs to return a value of the
    dependent variable, yint, at a given value of the
    independent variable, xx.
    Input:
        x = array of independent variable values
        y = array of dependent variable values
        xx = value of independent variable at which
             the interpolation is calculated
    Output:
        yint = interpolated value of the dependent variable
    """
    # compute the finite divided differences in the 
    # form of a difference table
    n = len(x)
    if len(y) != n:
        return 'x and y must be of same length'
    b = np.zeros((n,n))
    # assign the dependent variables to the first column of b
    b[:,0] = np.transpose(y)
    for j in range(1,n):
        for i in range(n-j):
            b[i,j] = (b[i+1,j-1]-b[i,j-1])/(x[i+j]-x[i])
    # use the finite divided differences to interpolate
    xt = 1
    yint = b[0,0]
    for j in range(n-1):
        xt = xt * (xx - x[j])
        yint = yint + b[0,j+1]*xt
    return yint



In [22]:
# Approximate the logarithm of a number using Newton's interpolation
x = np.array([1., 4., 6., 5.])
y = np.log(x)
yi = Newtint(x, y, 2.)
print(yi)
# Calculate the logarithm directly for comparison and print the relative error in percentage
log_direct = np.log(2.)
print(f"Direct log(2) value: {log_direct}")
print(f"Error in interpolation: {yi - log_direct}")
print(f"Relative error in interpolation: {(yi - log_direct) / log_direct * 100:.2f}%")


0.6287685789084135
Direct log(2) value: 0.6931471805599453
Error in interpolation: -0.06437860165153175
Relative error in interpolation: -9.29%


In [23]:
# Example interpolation with Vandermonde matrix. Calculate the error just as above
# Create the Vandermonde matrix and solve for polynomial coefficients
x = np.array([1., 4., 6., 5.])
y = np.log(x)
n = len(x)
A = np.vander(x, N=n)
coeffs_vander = np.linalg.solve(A, y)

# Use polyval to evaluate the polynomial at the new point
y_new_vander = np.polyval(coeffs_vander, 2.)
print(f"Estimated value at x = 2 (Vandermonde): {y_new_vander}")
# Calculate the logarithm directly for comparison
log_direct_vander = np.log(2.)
print(f"Direct log(2) value (Vandermonde): {log_direct_vander}")
print(f"Error in interpolation (Vandermonde): {y_new_vander - log_direct_vander}")
print(f"Relative error in interpolation (Vandermonde): {(y_new_vander - log_direct_vander) / log_direct_vander * 100:.2f}%")

Estimated value at x = 2 (Vandermonde): 0.6287685789084143
Direct log(2) value (Vandermonde): 0.6931471805599453
Error in interpolation (Vandermonde): -0.06437860165153098
Relative error in interpolation (Vandermonde): -9.29%


In [24]:
# Repeat the comparison above with Newton and Vandermonde methods but using only 3 points
# Print the relative error in both cases (Newton and Vandermonde)
# Example interpolation with Vandermonde matrix. Calcualate the error just as above
# Create the Vandermonde matrix and solve for polynomial coefficients
x = np.array([1., 4., 6.])
y = np.log(x)
n = len(x)
A = np.vander(x, N=n)
coeffs_vander = np.linalg.solve(A, y)       

# Use polyval to evaluate the polynomial at the new point
y_new_vander = np.polyval(coeffs_vander, 2.)
print(f"Estimated value at x = 2 (Vandermonde with 3 points): {y_new_vander}")
# Calculate the logarithm directly for comparison
log_direct_vander = np.log(2.)
print(f"Direct log(2) value (Vandermonde with 3 points): {log_direct_vander}")
print(f"Error in interpolation (Vandermonde with 3 points): {y_new_vander - log_direct_vander}")
print(f"Relative error in interpolation (Vandermonde with 3 points): {(y_new_vander - log_direct_vander) / log_direct_vander * 100:.2f}%")      

Estimated value at x = 2 (Vandermonde with 3 points): 0.5658443469009825
Direct log(2) value (Vandermonde with 3 points): 0.6931471805599453
Error in interpolation (Vandermonde with 3 points): -0.12730283365896278
Relative error in interpolation (Vandermonde with 3 points): -18.37%


In [25]:
# Now with Newton's method using 3 points
yi_newt = Newtint(x, y, 2.)
print(f"Estimated value at x = 2 (Newton with 3 points): {yi_newt}")
# Calculate the logarithm directly for comparison
log_direct_newt = np.log(2.)
print(f"Direct log(2) value (Newton with 3 points): {log_direct_newt}")
print(f"Error in interpolation (Newton with 3 points): {yi_newt - log_direct_newt}")
print(f"Relative error in interpolation (Newton with 3 points): {(yi_newt - log_direct_newt) / log_direct_newt * 100:.2f}%")

Estimated value at x = 2 (Newton with 3 points): 0.5658443469009827
Direct log(2) value (Newton with 3 points): 0.6931471805599453
Error in interpolation (Newton with 3 points): -0.12730283365896256
Relative error in interpolation (Newton with 3 points): -18.37%


## Lagrange Interpolation

In [26]:
import numpy as np

def Lagrange(x,y,xx):
    """
    Lagrange interpolating polynomial
    Uses an (n-1)th-order Lagrange interpolating polynomial
    based on n data pairs to return a value of the
    dependent variable, yint, at a given value of the
    independent variable, xx.
    Input:
        x = array of independent variable values
        y = array of dependent variable values
        xx = value of independent variable at which
             the interpolation is calculated
    Output:
        yint = interpolated value of the dependent variable
    """
    n = len(x)
    if len(y) != n:
        return 'x and y must be of same length'
    s = 0
    for i in range(n):
        product = y[i]
        for j in range(n):
            if i != j:
                product = product * (xx - x[j])/(x[i]-x[j])
        s = s + product
    yint = s
    return yint


In [27]:
# Example interpolation with Lagrange polynomial
# create a table with Temperature and density values
# and interpolate at a given temperature
# This is an example similar to the one in the book with Python syntax
T = np.array([-40., 0., 20., 50.])
rho = np.array([1.52, 1.29, 1.2, 1.09])
rhoint = Lagrange(T,rho,15.)
print(rhoint)

1.2211284722222222
